#!/usr/bin/env bash
#this script send a file to the server using a private key
scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa /home/ubuntu97/Desktop/some_page.html ubuntu@3.90.27.81:~/some_page.html
